//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCJQ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int Rno { get; set; }
        public string Name { get; set; }
        public Nullable<double> English { get; set; }
        public Nullable<double> Maths { get; set; }
        public Nullable<double> Science { get; set; }
    }
}
